#!/usr/bin/env bash

function bootstrap {
  local shome="${_virtualbox_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      block compile dmg \
        'http://download.virtualbox.org/virtualbox/5.0.20/VirtualBox-5.0.20-106931-OSX.dmg' \
        'VirtualBox' 'VirtualBox.pkg'
      ;;
    Linux)
      sudo apt-key add "$shome/etc/virtualbox.gpg"
      echo 'deb http://download.virtualbox.org/virtualbox/debian trusty contrib' | sudo tee /etc/apt/sources.list.d/virtualbox.list
      sudo aptitude update
      sudo aptitude install -y dkms virtualbox-5.0
      ;;
  esac
}

bootstrap
