#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      app compile dmg \
        'http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14-105127-OSX.dmg' \
        'VirtualBox' 'VirtualBox.pkg'
      ;;
    Linux)
      curl -sS -L 'https://www.virtualbox.org/download/oracle_vbox.asc' | sudo apt-key add -
      echo 'deb http://download.virtualbox.org/virtualbox/debian trusty contrib' | sudo tee /etc/apt/sources.list.d/virtualbox.list
      sudo aptitude update
      sudo aptitude install -y dkms virtualbox-5.0
      ;;
  esac
}

bootstrap
