#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.virtualbox')" == "$VIRTUALBOX_VERSION" ]]; then
    return 0
  fi

  if facts -e '(.virtualization_role == "guest")' >/dev/null; then
    return 0
  fi

  return 1
}

source sub "$BASH_SOURCE" "$@"
