#!/usr/bin/env bash

function _virtualbox_profile {
  local shome="${_virtualbox_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH:/usr/local/bin"
}

_virtualbox_profile
