#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      if facts -e '(.virtualization_role == "guest")' >/dev/null; then
        return 1
      fi
      ;;
  esac

  if [[ -x "$(type -P VBoxManage)" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"
