#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  VBoxManage hostonlyif ipconfig vboxnet0 -ip "$CACHE_VIP"
}

main "$@"
